// $ASHEM — parse the latest entry of state/endgame-health.md.
//
// That file is generated by scripts/health-report.sh at the end of every endgame.yml
// run (every 6h), append-only. Cowork already reads it off the public raw URL; the
// bot reads the same source so there's one source of truth. We parse the LAST
// "## Endgame health — <ts>" block, since the file is append-only.

import { healthUrl } from './config';

export interface HealthEntry {
  timestamp: string | null;
  status: string | null; // 🟢 / 🟡 / 🔴
  runUrl: string | null;
  harvest: string | null;
  circuitBreaker: string | null;
  buffer: string | null; // raw "Buffer dinámico:" line body
  stateMachine: string | null; // e.g. IDLE, HARVEST_SPLIT
  idempotency: string | null;
  anomaly: string | null;
  detail: string | null;
  /** accumulated burned / dev, in base units, parsed out of the detail line when present */
  cumulativeBurnedRaw: string | null;
  cumulativeDevRaw: string | null;
  raw: string;
}

function field(block: string, label: string): string | null {
  // matches "**Label:** value" up to end of line
  const re = new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`, 'i');
  const m = block.match(re);
  return m ? m[1].trim() : null;
}

export async function fetchLatestHealth(): Promise<HealthEntry> {
  const res = await fetch(healthUrl(), {
    signal: AbortSignal.timeout(8000),
    // raw.githubusercontent is CDN-cached ~5 min; that's acceptable for a 6h cadence.
    cache: 'no-store',
    headers: { 'User-Agent': 'ashem-discord-bot' },
  });
  if (!res.ok) throw new Error(`health log HTTP ${res.status}`);
  const text = await res.text();

  // Split on the entry header and take the last non-empty block.
  const parts = text.split(/^##\s+Endgame health\s+—\s+/m);
  const last = parts[parts.length - 1] ?? '';
  const block = last.trim();

  const firstLine = block.split('\n')[0] ?? '';
  const timestamp = firstLine.trim() || null;

  const detail = field(block, 'Detalle libre');
  let cumulativeBurnedRaw: string | null = null;
  let cumulativeDevRaw: string | null = null;
  if (detail) {
    const b = detail.match(/quemado=(\d+)/);
    const d = detail.match(/dev=(\d+)/);
    cumulativeBurnedRaw = b ? b[1] : null;
    cumulativeDevRaw = d ? d[1] : null;
  }

  const stateLine = field(block, 'Máquina de estados');
  const stateMachine = stateLine ? (stateLine.match(/^([A-Z_]+)/)?.[1] ?? stateLine) : null;

  return {
    timestamp,
    status: field(block, 'Semáforo'),
    runUrl: field(block, 'Run revisado'),
    harvest: field(block, 'Harvest'),
    circuitBreaker: field(block, 'Circuit breaker'),
    buffer: field(block, 'Buffer dinámico'),
    stateMachine,
    idempotency: field(block, 'Idempotencia'),
    anomaly: field(block, 'Anomalía vs. falla de harvest conocida'),
    detail,
    cumulativeBurnedRaw,
    cumulativeDevRaw,
    raw: block,
  };
}

/** base units (9 decimals) → whole ASHEM tokens */
export function baseUnitsToTokens(raw: string | null): number | null {
  if (!raw) return null;
  try {
    return Number(BigInt(raw)) / 1e9;
  } catch {
    return null;
  }
}
